### ISSUE TITLE
Please support paired input to bowtie2.

### ISSUE THREAD

**Issue by charles-plessy** [nf-core/eager#652] opened 2021-01-08 06:32 UTC
# nf-core/eager feature request

Hello, thank you very much for providing this pipeline. While not working on ancient DNA, I use it to QC genomic libraries and find it extremely useful.

## Is your feature request related to a problem? Please describe

I am using paired-end data with insert size too large for collapsing Read1 and Read2, and I could not find a way to make `bowtie2` align in paired-end mode.

Paired-end alignment is important for me because I sequence at deep coverage, therefore single-end alignment overestimates the amount of sequence duplicates.

## Describe the solution you'd like

Can you support paired input to `bowtie2`?

## Describe alternatives you've considered

`eager` does not seem to support paired-end alignment with other software, and `bowtie2` is better for me because I have read lengths of 150 nt. 

Have a nice day,

Charles

**Comment by jfy133** [comment] 2021-01-08 07:58
Hi @charles-plessy .

Happy to hear it's useful in other contexts 

 I'm on lockdown childcare duty today so can't look more closely atm. But I believe we do already offer this (unless I'm misunderstanding). Line 1666 of main.nf shows that in principle, if you `--skip_collapse` you will do a paired end mapping.

Let me know if that isn't what you meant or it didn't work

**Comment by charles-plessy** [comment] 2021-01-12 05:40
It worked very well, thank you! Please document explicitly on the Usage docs page that this option is needed to turn on paired-end alignment; I would not have been able to find the information without your help.

**Comment by jfy133** [comment] 2021-01-12 12:11
Hi @charles-plessy OK cool, glad to hear!

Hmm, honestly I'm not really 100% where I would put this... given it is somewhat implicit (you don't have to 'turn on' paired-end mapping, it just will do it by default as this is the nature of the specificed input data), and it would be rarely used in ancient DNA (I've never used it myself), I'm a bit unsure where the logical place would be.

If you have any suggestions where you would intiuitively look for this information, please let me know and I can add it (or even better, make a PR!). I will close this issue as the issue is solved, but feel to reply on this issue with any suggestions.

**Closed by jfy133** 2021-01-12 12:11 UTC
Labels: enhancement, user-support
